services:
  database:
    platform: linux/x86_64
    container_name: BGP-Database
    build:
      context: .
      dockerfile: Dockerfile-ls-db
    ports:
      - "3453:3306"
  lobby:
    container_name: BGP-Lobby
    build:
      context: .
      dockerfile: Dockerfile-ls-api
    ports:
      - "4242:4242"
    depends_on:
      - database
    command: sh -c "/wait && java -jar /usr/app/ls.jar"
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
  xox:
    container_name: BGP-Xox
    build:
      context: .
      dockerfile: Dockerfile-ls-xox
    ports:
      - "4244:4244"
    depends_on:
      - lobby
    command: sh -c "/wait && java -jar /usr/app/xox.jar"
    environment:
      - WAIT_HOSTS=lobby:4242
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
version: '3.8'

